const ROOM_HEIGHT = 9;
const ROOM_WIDTH = 9;
const TILE_SIZE = 16;
const MAX_LIGHT_DISTANCE = 5;
const MAX_FLARE_DISTANCE = 3;

export { ROOM_HEIGHT, ROOM_WIDTH, TILE_SIZE, MAX_LIGHT_DISTANCE, MAX_FLARE_DISTANCE };